---
- name: My Test Playbook
  hosts: all
  become: true

  tasks:
  - name: Installing httpd package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Start httpd service
    service:
      name: htt--
      state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes

  - name: Installing apche2 package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copy index.html
    copy:
      src: index.html
      dest: /var/www/html
      mode: 0666
